### ISSUE TITLE
Deprecation of signrawtransaction method

### ISSUE THREAD

**Issue by volbil** [y-chan/atomicswap-qt#12]
Just noticed that `signrawtransaction` method is [deprecated](https://github.com/bitcoin/bitcoin/blob/0.17/src/rpc/rawtransaction.cpp#L1057-L1061) since Bitcoin 0.17. We should add additional checks and make possible to sign transaction with `signrawtransactionwithwallet` method.

**Comment by volbil** [comment]
Seams like `signrawtransactionwithwallet` is fairly similar to `signrawtransaction` so it won't be an issue.

**Comment by volbil** [comment]
Ah, seams like you already fixed this :)

**Comment by y-chan** [comment]
I control sign_wallet flag by wallet version.
Look at this.
https://github.com/y-chan/atomicswap-qt/blob/master/atomicswap/qt/atomicswap_window.py#L466
req_ver is req_ver in coin config json.
version is coin core version by coind rpc.
Set sign_wallet flag to True if version satisfies req_ver.

**Comment by volbil** [comment]
Oh, I see, thanks for info. But I think it's would be nice anyway to have this as configurable option. What do you think about it?

**Comment by volbil** [comment]
For example if coin config file has an sign_wallet field, use it, otherwise check wallet version.

**Comment by y-chan** [comment]
I see. I think that your idea is good. I'll try to implement

**Comment by volbil** [comment]
@y-chan don't worry, I will add this to my PR

**Comment by volbil** [comment]
Done https://github.com/y-chan/atomicswap-qt/pull/13/commits/89600a73203249c1e4db9feb426d3c24b6bec074

**Comment by volbil** [comment]
So, by default `coind.sign_wallet` is set to `False`, so it make sense to check `req_ver` only if `sign_wallet` is still `False`.

**Comment by volbil** [comment]
You can check PR #13

**Comment by y-chan** [comment]
ohhhhhh.
thanks!
I make commit 😅 
https://github.com/y-chan/atomicswap-qt/commit/03afc40d10032ee4851417a491eb5ab5e6cbb2ab

**Comment by volbil** [comment]
Thanks @y-chan :)
