### ISSUE TITLE
Ability to delete entry from history

### ISSUE THREAD

**Issue by volbil** [y-chan/atomicswap-qt#16]
It would be nice to have option of removing swap from history. 
![Example](https://i.imgur.com/NnGyCm3.png)

**Comment by y-chan** [comment]
Hum...ok, I'll Consider it

**Comment by y-chan** [comment]
![image](https://user-images.githubusercontent.com/34832037/72352648-fd3a5e80-3725-11ea-811a-951c4dac1fe6.png)
![image](https://user-images.githubusercontent.com/34832037/72352660-04fa0300-3726-11ea-8dfd-1321e3c25e00.png)
I implemented it.

**Comment by volbil** [comment]
Thanks @y-chan :)
