### ISSUE TITLE
Quotes code style

### ISSUE THREAD

**Issue by volbil** [y-chan/atomicswap-qt#19]
I've noticed little inconsistency in quote styles, we using mixed `"` and `'` quotes for string definiton. It would be nice to have consystent quotes style. I'm personally preffer single quote sign since code looks cleaner this way :)

What you think about it @y-chan ?

**Comment by y-chan** [comment]
I'll fix it, sorry.
Thanks.

**Comment by volbil** [comment]
@y-chan nah, you don't have to be sorry, I just want to know what quotes you preffer to use :swea

**Comment by y-chan** [comment]
Oh, i see.
I usually use `"`.
I rarely use `'`, but it got mixed up when copying the code.
Sorry.

**Comment by volbil** [comment]
@y-chan got it, I will do the clean up soon and will user `"` :)

**Comment by y-chan** [comment]
Thanks.
